Initial template for classes
Jlrine2/CS372-CPS pull request #4
Opened 2020-03-24 22:52 UTC by scifi6546

Wrote initial template. Not too experienced with c++ polymorphism so there may be some mistakes.

2020-03-24 23:06 UTC, Jlrine2 commented on src/cps.hpp
> +    virtual std::iostream draw()=0;
Should this be `virtual std::iostream draw() {};

2020-03-25 18:05 UTC, Jlrine2 requested changes

2020-03-25 18:05 UTC, Jlrine2 commented on src/cps.hpp
> +class Polygon: Shape{
Tried using this code, looks good but I needed to add public to each of these in order to be able to use them

```c++
class Polygon: public Shape {};
```

2020-03-25 18:11 UTC, Jlrine2 commented on src/cps.hpp
> +class Polygon: Shape{
see: https://github.com/Jlrine2/CS372-CPS/pull/5

2020-03-25 20:36 UTC, scifi6546 reviewed
That looks a lot better

2020-03-25 20:40 UTC, Jlrine2 approved these changes

2020-03-25 20:40 UTC, merged